#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/messenger_db
#    username: postgres
#    password: root
#  jpa:
#    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate.ddl-auto: update
#      hibernate.jdbc.time_zone: UTC
#      hibernate.id.new_generator_mappings: true
#      hibernate.connection.provider_disables_autocommit: true
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false
#      # modify batch size as necessary
#      hibernate.jdbc.batch_size: 25
#      hibernate.order_inserts: true
#      hibernate.order_updates: true
#      hibernate.query.fail_on_pagination_over_collection_fetch: true
#      hibernate.query.in_clause_parameter_padding: true
#


spring:
  banner:
      location: classpath:static/banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8080